version: "3.5"
services:
  test-pages:
    image: nginx:alpine
    ports:
      - "9090:80"
    volumes:
      - "./test-pages:/usr/share/nginx/html:ro"

  prebid-server:
    restart: on-failure
    build:
      context: ./prebid-server
      args:
        server_source: "${PREBID_SERVER_SOURCE}"
        server_branch: "${PREBID_SERVER_BRANCH}"
    ports:
      - "8000:8000"
      - "8080:8080"
    env_file:
      - prebid-server.env

  build-prebid-js:
    build: ./build-prebid-js
    command: "/var/build/build.sh"
    environment:
      PREBID_JS_SOURCE: "${PREBID_JS_SOURCE}"
      PREBID_JS_BRANCH: "${PREBID_JS_BRANCH}"
      BUILD_DIR: "/tmp/prebid"
      BUILD_TARGET: "/var/result"
      BUILD_STAGE: "dev" # "prod" otherwise

    volumes:
      - "./test-pages/prebid.js:/var/result"
      - "./build-prebid-js:/var/build"
